OPENEUROPA-1642: Create AVPortal resource url service and move url logic.
openeuropa/media_avportal pull request #13
Opened 2019-02-21 15:52 UTC by hernani

## OPENEUROPA-1642

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-02-22 10:50 UTC, imanoleguskiza submitted a review, later dismissed

2019-02-22 15:26 UTC, sergepavle commented on src/Plugin/Field/FieldWidget/AvPortalWidget.php
> +   * @var |Drupal\media_avportal\Plugin\media\Source\MediaAvPortalSourceInterface
typo

2019-02-22 15:35 UTC, sergepavle reviewed
I have found just little typo.
Everything else is good.

2019-02-25 09:42 UTC, upchuk requested changes

2019-02-25 09:42 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalSourceInterface.php
> +  public function getSupportedUrlsFormat(): array;
`getSupportedUrlFormats`

2019-02-25 09:42 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalSourceInterface.php
> +  public function getSupportedUrlsPatterns(): array;
`getSupportedUrlPatterns`

2019-02-25 09:42 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalPhotoSource.php
> +  public function getSupportedUrlsFormat() : array {
Colon right after function name (consistent with the rest of the places)

2019-02-25 09:42 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalPhotoSource.php
> +  public function getSupportedUrlsPatterns() : array {
Colon right after function name (consistent with the rest of the places)

2019-02-25 09:42 UTC, upchuk commented on src/Plugin/Field/FieldWidget/AvPortalWidget.php
> +    $referenceUrl = reset($formats);
`reference_url`

2019-02-25 12:40 UTC, upchuk requested changes

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/Field/FieldWidget/AvPortalWidget.php
> +    $reference_url = reset($formats);
This is not used anywhere anymore.

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/Field/FieldWidget/AvPortalWidget.php
> +   * @var |Drupal\media_avportal\Plugin\media\Source\MediaAvPortalSourceInterface
@hernani yes, typo :)

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/Field/FieldWidget/AvPortalWidget.php
> +    if ($this->source instanceof MediaAvPortalSourceBase) {
The source is always going to be an instance of this because above we rely on that to get the format. So this `if` is not needed.

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalPhotoSource.php
> +  public function transformUrlToReference(array $url): ?string {
This should return a string in all cases, even if no matches are found.

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalPhotoSource.php
> +  public function transformReferenceToUrl(string $reference): ?string {
This should return a string in all cases, even if no matches are found.

Also, no need for empty line at the beginning of the method.

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalSourceInterface.php
> +  public function transformUrlToReference(array $url): ?string;
Why do we intake an array for URL here? Can we not just get the URL itself?

If we really need to take an array, then we need to thoroughly document the components of this expected array. Also, usually a bad idea to pass data like this in array.

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalVideoSource.php
> +    $formats = $this->getSupportedUrlFormats();
This should return a string in all cases, even if no matches are found.

Also, no need for empty line at the beginning of the method.

2019-02-25 12:40 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalVideoSource.php
> +  public function transformUrlToReference(array $url): ?string {
This should return a string in all cases, even if no matches are found.

2019-02-26 08:34 UTC, upchuk approved these changes

2019-02-26 08:35 UTC, sergepavle commented on src/Plugin/Field/FieldWidget/AvPortalWidget.php
> +    $patterns = $element['#valid_urls'];
Probably we don't need even declare $patterns

2019-02-26 12:35 UTC, sergepavle approved these changes

2019-02-26 12:36 UTC, merged