OPENEUROPA-1725: Adapt AV Portal URL.
openeuropa/media_avportal pull request #16
Opened 2019-03-27 17:02 UTC by hernani

## OPENEUROPA-1725

### Description

Adapt AV Portal URL.

2019-04-01 14:08 UTC, imanoleguskiza submitted a review, later dismissed

2019-04-02 12:07 UTC, upchuk requested changes
Let's also change the constraint validation message to:

```
The given URL does not match an AV Portal resource.
```

2019-04-02 12:07 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalPhotoSource.php
> +      '@audiovisual\.ec\.europa\.eu/(.*)/photo/(P\-.*\~2F.*)@i' => 'transformFullUrlToReference',
The API of this method has changed. We need to also update the docs on the interface.

Also, since the `transformFullUrlToReference` is always gonna be needed, and has the same name, can't we just assume it and simply use it to transform a *url* to a *reference*? Meaning that we don't need to pass a callback from the `getSupportedUrlPatterns()`

2019-04-02 12:07 UTC, upchuk commented on src/Plugin/media/Source/MediaAvPortalPhotoSource.php
> +   * Callback function to transform url to a reference.
`Callback function to transform a URL to a reference.`. And based on my previous comment, this could go on the interface and implemented by each source with their respective logic. No?

2019-04-02 13:54 UTC, upchuk submitted a review, later dismissed

2019-04-02 14:00 UTC, upchuk submitted a review, later dismissed

2019-04-02 14:06 UTC, upchuk submitted a review, later dismissed

2019-04-02 14:07 UTC, imanoleguskiza submitted a review, later dismissed

2019-04-02 14:25 UTC, upchuk approved these changes

2019-04-02 14:31 UTC, imanoleguskiza approved these changes

2019-04-02 14:31 UTC, merged