OPENEUROPA-2052: Add supporting of AV Portal URLs with album.
openeuropa/media_avportal pull request #28
Opened 2019-07-30 12:11 UTC by sergepavle

## OPENEUROPA-2052

### Description

Actual result:

As a CMS user 
When I visit "the media/add/av_portal_photo"
And I fill in Media AV Portal Photo with https://audiovisual.ec.europa.eu/en/album/M-000758/P-026777~2F00-02
And I press Save
Then I receive an error "Invalid URL format specified." (see attachment)

Expected result:

As a CMS user
When I visit "the media/add/av_portal_photo"
I should be able to add https://audiovisual.ec.europa.eu/en/album/M-000758/P-026777~2F00-02 as a media file

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-07-30 13:00 UTC, imanoleguskiza requested changes

2019-07-30 13:00 UTC, imanoleguskiza commented on tests/src/FunctionalJavascript/MediaAvPortalCreateContentTest.php
> +    // We could update photo with different URL formats supporting.
I think this comment should go before the $photo_urls variable is set and a better phrasing would be: "We need to support both individual photos and photos inside albums"

2019-07-30 13:00 UTC, imanoleguskiza commented on tests/src/FunctionalJavascript/MediaAvPortalCreateContentTest.php
> +      // Update the field with url from album.
We test both album and alone photos, so no need to change this comment from "Update the field."

2019-07-30 13:05 UTC, imanoleguskiza approved these changes

2019-07-31 13:28 UTC, nagyad approved these changes

2019-07-31 13:29 UTC, merged