OPENEUROPA-2165: [media_avportal] Missing information for some videos.
openeuropa/media_avportal pull request #31
Opened 2019-08-20 13:19 UTC by sergepavle

## OPENEUROPA-2165

### Description

Some videos have a different response format, thus the current code cannot retrieve the correct metadata from them. Quite a few examples were found by AMPATZIS Ioannis:

no thumbnail: https://audiovisual.ec.europa.eu/en/video/I-129872 https://audiovisual.ec.europa.eu/en/video/I-098040
no title: https://audiovisual.ec.europa.eu/en/video/I-053547 https://audiovisual.ec.europa.eu/en/video/I-001464
no thumbnail AND title: https://audiovisual.ec.europa.eu/en/video/I-056847
The reason seems a different format for the json response. Scope of the ticket is to cover these cases.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-08-21 11:32 UTC, imanoleguskiza submitted a review, later dismissed

2019-08-21 11:32 UTC, imanoleguskiza submitted a review, later dismissed

2019-08-30 07:14 UTC, brummbar requested changes
Let's add a service that allows to refresh existing avportal media entities so websites can refresh their data if needed.

2019-08-30 07:14 UTC, brummbar commented on tests/src/FunctionalJavascript/MediaAvPortalCreateContentTest.php
> +      [
Let's add the key here so we can specify what we are testing, like "Video with no title"

2019-08-30 07:14 UTC, brummbar commented on src/AvPortalResource.php
> +    if (isset($first_media_json['INT']['THUMB'])) {
Let's add an extra fallback here. After checking if the international version is available, check for the current site language. Then return the first available in the languages array.

2019-09-19 08:51 UTC, hernani approved these changes
Approved.

2019-09-19 08:53 UTC, brummbar approved these changes

2019-09-19 08:53 UTC, merged