OPENEUROPA-2168: Update field description.
openeuropa/media_avportal pull request #33
Opened 2019-09-10 16:33 UTC by sergepavle

## OPENEUROPA-2168

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-09-11 09:22 UTC, imanoleguskiza submitted a review, later dismissed

2019-09-12 06:50 UTC, upchuk requested changes
We don't have test coverage for this. Let's include please in the existing test a short case for the album photo. This will probably mean adding a new fixture photo.

2019-09-12 07:36 UTC, sergepavle commented
> We don't have test coverage for this. Let's include please in the existing test a short case for the album photo. This will probably mean adding a new fixture photo.

But we have. I reuse existing fixture.
https://github.com/openeuropa/media_avportal/blob/8.x-1.x/tests/src/FunctionalJavascript/MediaAvPortalCreateContentTest.php#L173

2019-09-12 13:52 UTC, upchuk approved these changes

2019-09-13 07:07 UTC, nagyad approved these changes

2019-09-13 07:07 UTC, merged