OPENEUROPA-2661: Specify preferred thumbnail resolution.
openeuropa/media_avportal pull request #41
Opened 2020-01-16 14:12 UTC by nagyad

2020-01-17 08:16 UTC, sergepavle submitted a review, later dismissed

2020-01-20 08:23 UTC, brummbar requested changes
The implementation is done correctly following my requests, but it misses tests.
Anyway, after discussion with the coordination team, we agreed that the thumbnail resolution is available only for images and not videos, but the public method `getThumbnailUrl()` is used for both.
So we cannot put a parameter on it as videos don't have a size. Let's revert all the code, and just change the order on which the thumbnails are returned: MID, LOW, HIGH.
Provide also tests to check the thumbnails resolution order.

2020-01-20 12:46 UTC, brummbar requested changes
We need a unit test to cover all the code of the `getThumbnailUrl()` method.

2020-01-21 12:46 UTC, brummbar requested changes

2020-01-21 12:46 UTC, brummbar commented on tests/src/Unit/AvPortalResourceTest.php
> +  public function testAvPortalPhotoThumbnailUrl(): void {
```suggestion
  public function testGetPhotoThumbnailUrl(): void {
```

2020-01-21 12:46 UTC, brummbar commented on tests/src/Unit/AvPortalResourceTest.php
> +   * Tests the photo thumbnail preferred resolution.
We actually test the whole `getPhotoThumbnailUrl()` method in here, so let's update the phpdoc.

2020-01-21 12:46 UTC, brummbar commented on tests/src/Unit/AvPortalResourceTest.php
> +      'doc_ref' => 'P-038924',
Let's put only the minimum amount of data needed for this test. Let's remove the line `doc_ref`.

2020-01-21 12:46 UTC, brummbar commented on tests/src/Unit/AvPortalResourceTest.php
> +      'titles_json' =>
Let's remove also the titles.

2020-01-21 12:46 UTC, brummbar commented on tests/src/Unit/AvPortalResourceTest.php
> +      'summary_json' =>
Also summary.

2020-01-21 12:46 UTC, brummbar commented on tests/src/Unit/AvPortalResourceTest.php
> +      'shootstartdate' => '20181130 00:00',
Also shootstartdate.

2020-01-22 08:25 UTC, brummbar requested changes

2020-01-22 08:25 UTC, brummbar commented on tests/src/Unit/AvPortalResourceTest.php
> +   * Tests getThumbnailUrl() method.
```suggestion
   * Tests the testGetPhotoThumbnailUrl() method.
```
As I wrote in my previous review, we are testing the `getPhotoThumbnailUrl()` method. The `getThumbnailUrl()` method covers also videos.

I noticed now that the `getPhotoThumbnailUrl()` method would be used when the type is `PHOTO` or `REPORTAGE`. Let's add a `@dataProvider` called `photoTypeDataProvider()` method that returns `PHOTO` and `REPORTAGE` and let's use it in this method to check that it would work correctly.

2020-01-22 12:31 UTC, brummbar approved these changes

2020-01-23 07:11 UTC, upchuk approved these changes

2020-01-23 07:11 UTC, merged