OPENEUROPA-2968: AV Portal photo name shows encoded characters in Media list
openeuropa/media_avportal pull request #47
Opened 2020-03-13 15:33 UTC by sergepavle

## OPENEUROPA-2968

### Description
https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-2968

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-03-16 08:54 UTC, 22Alexandra submitted a review, later dismissed

2020-03-16 14:56 UTC, brummbar requested changes
We have a unit test now, let's cover the getTitle() method in that one and avoid doing it in the browser one.

2020-03-17 13:01 UTC, 22Alexandra submitted a review, later dismissed

2020-03-24 09:03 UTC, 22Alexandra approved these changes

2020-03-24 11:17 UTC, brummbar approved these changes

2020-03-24 11:17 UTC, merged