EWPP-1850: Testing that the video iframe URL gets the correct language code.
openeuropa/media_avportal pull request #70
Opened 2022-01-27 13:28 UTC by upchuk

2022-01-31 10:59 UTC, nagyad requested changes

2022-01-31 10:59 UTC, nagyad commented on tests/src/FunctionalJavascript/MediaAvPortalCreateContentTest.php
> +    // Switch to FR and assert the changed urL language.
url...

2022-01-31 10:59 UTC, nagyad commented on tests/src/FunctionalJavascript/MediaAvPortalCreateContentTest.php
> +    // Switch to PT and assert the changed urL language.
url...

2022-01-31 12:39 UTC, nagyad approved these changes

2022-02-01 10:16 UTC, nagyad requested changes
1. phpcs error needs to be addressed.
2. EWCMS PR is missing and tests.

2022-02-01 10:45 UTC, yenyasinn approved these changes, later dismissed

2022-02-01 16:37 UTC, nagyad approved these changes, later dismissed

2022-02-08 14:02 UTC, yenyasinn approved these changes

2022-02-08 14:29 UTC, nagyad approved these changes

2022-02-08 14:32 UTC, merged