EWPP-1911: PHP8 compatibility.
openeuropa/media_avportal pull request #71
Opened 2022-02-03 16:02 UTC by nagyad

2022-02-03 16:09 UTC, nagyad reviewed
.info.yml needs to be updated too. Reopening.

2022-02-03 16:09 UTC, nagyad commented on composer.json
> +            "dealerdirect/phpcodesniffer-composer-installer": true
Should be in alphabetic order.

2022-02-04 10:38 UTC, 22Alexandra requested changes

2022-02-04 10:38 UTC, 22Alexandra commented on media_avportal.info.yml
> +core_version_requirement: ^9.2
Please update test modules too.

2022-02-04 10:38 UTC, 22Alexandra commented on .drone.yml
> +    - composer self-update --2
We can remove the `--no-suggest`

2022-02-04 10:38 UTC, 22Alexandra commented on composer.json
>          "symfony/mime": "^4.3|^5.0"
We can remove this and its readme entry.

2022-02-04 10:38 UTC, 22Alexandra commented on composer.json
> +        "phpunit/phpunit": "^9.4"
We don't need this.

2022-02-04 13:44 UTC, 22Alexandra approved these changes

2022-02-07 10:35 UTC, hernani approved these changes

2022-02-07 10:36 UTC, merged